### ISSUE TITLE
Android crash: java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by zhpoo** [line/flutter_line_sdk#19]
## What did you do?

Click button and call 
``` 
final LoginResult result = await LineSDK.instance.login(
        scopes: ["profile", "openid", "email"],
      );
 ```
`and press Back button of android device quickly.`

## What did you expect?

Cancel the login-request.

## What happened actually?

> Crash.

## Your environment?

flutter_Line_sdk-1.2.6
android os 8.1.0

**Comment by zhpoo** [comment]
`
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=8192, result=0, data=null} to activity {com.***/com.***.MainActivity}: java.lang.IllegalStateException: Reply already submitted
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4774)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4818)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1844)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:167)
        at android.app.ActivityThread.main(ActivityThread.java:7146)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
     Caused by: java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
        at com.linecorp.flutter_line_sdk.LineSdkWrapper.handleActivityResult(LineSdkWrapper.kt:143)
        at com.linecorp.flutter_line_sdk.FlutterLineSdkPlugin.onActivityResult(FlutterLineSdkPlugin.kt:56)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:131)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
        at android.app.Activity.dispatchActivityResult(Activity.java:7553)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4770)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4818) 
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1844) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:167) 
        at android.app.ActivityThread.main(ActivityThread.java:7146) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820) 
`

**Comment by onevcat** [comment]
@tsairene Any idea on this?
